image:
  registry: ghcr.io
  repository: xstanler/mini-gitops-provisioner/demo-service
  tag: "69f9a42ccf34b36402c33fefe71ed2642552bcc6"

replicaCount: 1

container:
  port: 8000

service:
  port: 80
  targetPort: 8000
