image:
  registry: ghcr.io
  repository: xstanler/mini-gitops-provisioner/demo-service
  tag: "3955e3ac68ce3a9b425f16497c6a794b2338e307"

replicaCount: 1

container:
  port: 8000

service:
  port: 80
  targetPort: 8000
