image:
  registry: ghcr.io
  repository: xstanler/mini-gitops-provisioner/demo-service
  tag: "097fb6bebf515ccb601ca58a813365a6a5faefff"

replicaCount: 1

container:
  port: 8000

service:
  port: 80
  targetPort: 8000
