name: Build image and push to GHCR
on:
  push:
    branches:
      - master
      - DEVOPS-*

env:
  IMAGE_NAME: ghcr.io/xstanler/mini-gitops-provisioner/demo-service

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

        # 1. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

        # 2. Log in to GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: apps/demo-service
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Update Helm image tag
        run: |
          sed -i 's/tag: .*/tag: "${{ github.sha }}"/' charts/demo-service/values.yaml
      - name: Commit updated Helm values
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-action[bot]@users.noreply.github.com"

          git add charts/demo-service/values.yaml

          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update demo-service image tag to ${{ github.sha }}"
            git push
          fi


